# Generated by Django 4.0.3 on 2022-03-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('types', models.CharField(choices=[('ACTIVATE', 'ACTIVATE'), ('SUSPENDED', 'SUSPENDED'), ('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT'), ('OTHER', 'OTHER')], default='OTHER', max_length=20)),
            ],
        ),
    ]
