# Generated by Django 4.0.3 on 2022-03-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_is_notification_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_scheduled',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
