# Generated by Django 4.0.3 on 2022-03-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_notification_scheduled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_notification_cancelled',
            new_name='is_hide',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_scheduled',
            new_name='scheduled',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
