# Generated by Django 4.0.3 on 2022-03-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_rename_is_notification_cancelled_notification_is_hide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_hide',
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
